import datetime
today = datetime.datetime.now()
print("The today's date is :" ,today)
print(today.year)
print(today.month)
print(today.day)
print(today.hour)
print(today.minute)
print(today.second)
print(today.microsecond)
print(today.strftime("%A-%B-%Y"))
print(today.strftime("%d-%m-%y"))
print(today.min)
print(today.max)